---
title: "newdistlearn"
author: "Jessica Rico"
date: "3/6/2021"
output: 
  html_document: 
    keep_md: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if (!require("tidyverse")) install.packages('tidyverse')
```


```{r}
library(tidyverse)
library(rmarkdown)
library(shiny)
library(shinydashboard)
library(skimr)
library(janitor)
library(here)
library(RColorBrewer)
library(paletteer)
library(ggthemes)
library(naniar)
library(dplyr)
library(ggpubr)
options(scipen=999)
```


##Loading and Manipulating Datasets


#Attendance Rates Data


```{r}
test<- readr::read_csv("1920 attendance rates.csv")
test
```





```{r}
attrates<- readr::read_csv("att_rates.csv")
attrates

#This dataset shows the percent of student attendance for attendance months 1-5 by year. This also shows the number of students that both enrolled and withdrew from the school site in each of these months along with the total number of enrollment at each of these months. 
```


```{r}
attrates<- janitor::clean_names(attrates)
attrates$year<- as.factor(attrates$year)
attrates
```


#GPA by academic year

```{r}
gpa<- readr::read_csv("term_gpas.csv")
gpa<- janitor::clean_names(gpa)
gpa
```


```{r}
gpa%>%
  skimr::skim()
```


```{r}
gpa %>% 
  summarise_all(~(sum(is.na(.))))
```



```{r}
gpa2<- gpa%>%
  na.omit(gpa)
```



```{r}
gpa2 %>% 
  summarise_all(~(sum(is.na(.))))

```



```{r}
gpa2$year<- as.factor(gpa2$year)
gpa2

#This dataset shows the term 1 and term 2 grades for students by year. Term 1 represents progress grades and term 2 is the final semester grade. I removed the NA's that were present in the form of no values. These values coincided with students either withdrawing prior to receiving their posted grades or enrolling with less than 20 days between their enrollment and the grading period. 
```


#Attendance Codes by Year

```{r}
attreason <- readr::read_csv("att_reason_reports.csv")
attreason
```


```{r}
attcodes<- attreason%>%
  pivot_longer(-year, names_to = "att_code", values_to = "occurence")
attcodes$year<- as.factor(attcodes$year)
attcodes

#This dataset shows the usage of attendance codes by year. These attendance codes are used when we enter the reason behind an absence. Some, such as DR, ILL, are excused while others like UNV, and VUN are not excused. These factor in when it comes to determining our attendance percentages. The codes ILL19, AVP, NWFA, DAC, and NCA are codes introduced due to the pandemic. 
```
#Attempt to merge all datasets

```{r}
virtualed <- merge(attrates, attcodes,by="year")
virtualed
```




#Data



```{r}
attrates
```



```{r, eval=FALSE, echo=TRUE}
ui <- dashboardPage(
    dashboardHeader(title = "Attendance Rates, Enrollment and Withdrawal Data by Month"),
    dashboardSidebar(disable = F),
    dashboardBody(
        fluidRow(
            box(title = "Plot Options", width = 3,
                radioButtons("x", "Select Month", choices = c("1", "2", "3", "4", "5"), 
                             selected = "1"),
                selectInput("y", "Select Term", choices = c("attendance_rate_percent", "student_add", "student_drop"),
                            selected = "attendance_rate_percent"),
            ), # close the first box
            box(title = "Attendance Rates", "Enrollment and Withdrawal Data by Month", width=7,
                plotOutput("plot", width = "600px", height = "500px")
            ) # close the second box
        ) # close the row
    ) # close the dashboard body
) # close the ui

server <- function(input, output, session) { 
    
    output$plot <- renderPlot({
        attrates %>% 
            filter(month==input$x & attendance_rate_percent==input$y) %>% 
            ggplot(aes(x=month, fill=year)) +
            geom_histogram()+
            facet_wrap(~year)+
            #geom_col(color="black", fill="slateblue2", alpha=1)+
            theme_gdocs()+
            theme(axis.text.x = element_text(angle = 60, hjust = 1))
            #labs(x = "Month", y = "Number in Category")
    
})
    
    # stop the app when we close it
    session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```







```{r}
ui <- dashboardPage(
  dashboardHeader(title = "First Semester Attendance Rates 19/20 vs 20/21 "),
  dashboardSidebar(),
  dashboardBody(
  selectInput("y", "Select Filter", choices = c("attendance_rate_percent", "student_add", "student_drop"), selected = "attendance_rate_percent"),
  plotOutput("plot", width = "500px", height = "400px")))
dashboardBody(
  selectInput("x", "Select Filter", choices=c("month", "year"), selected="year"), 
  plotOutput("plot", width = "500px", height = "400px"))



server <- function(input, output, session) { 
 output$plot <- renderPlot({
  attrates %>% 
  ggplot(aes_string(x = "month", y = "attendance_rate_percent", fill=input$y)) +
  geom_col(position="dodge", alpha = 0.8, size=4)+
  theme_light(base_size = 18) + 
     labs(title= "Attendance and Enrollment by month", x="Attendance Month", y="Number of Students", fill = "Legend")+
     theme(axis.text.x = element_text(angle = 90, hjust = 1))
  })
  session$onSessionEnded(stopApp)
  }
shinyApp(ui, server)
```






```{r}
codesmonth<- readr::read_csv("ATTENDANCE CODES BY MONTH.csv")
codesmonth<- janitor::clean_names(codesmonth)
codesmonth
```







```{r}
attjoined<- merge(attrates, codesmonth,by=c("month", "year"))
attjoined$year <- as.numeric(attjoined$year)
attjoined
```




```{r, eval=FALSE, echo=TRUE}

ui <- dashboardPage(
    dashboardHeader(title = "GPA Stuff"),
    dashboardSidebar(disable = F),
    dashboardBody(
        fluidRow(
            box(title = "Plot Options", width = 3,
                radioButtons("x", "Select Month", choices = c("1", "2", "3", "4", "5"), 
                             selected = "1"),
                selectInput("y", "Select Factor", choices = c("student_attedance_percent", "student_add","student_drop", "used"),
                            selected = "student_attendance_percent"),
            ), # close the first box
            box(title = "GPA Stuff", width=7,
                plotOutput("plot", width = "600px", height = "500px")
            ) # close the second box
        ) # close the row
    ) # close the dashboard body
) # close the ui

server <- function(input, output, session) { 
    
    attjoined <- renderPlot({
        term_gpa_even_longer %>% 
            filter(month==input$x & number_of_students==input$y) %>% 
            ggplot(aes(x=month, fill=code)) +
            geom_histogram()+
            facet_wrap(~year)+
            #geom_col(color="black", fill="slateblue2", alpha=1)+
            theme_gdocs()+
            theme(axis.text.x = element_text(angle = 60, hjust = 1))
            #labs(x = "Data for Choice", y = "Number in Category")
    
})
    
    # stop the app when we close it
    session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```







```{r, eval=FALSE, echo=TRUE}

ui <- dashboardPage(
  dashboardHeader(title = "First Semester Attendance Rates 19/20 vs 20/21"),
  dashboardSidebar(),
  dashboardBody(
  selectInput("y", "Select Filter", choices = c("attendance_rate_percent", "student_add", "student_drop", "used"), selected = "attendance_rate_percent"),
  plotOutput("plot", width = "500px", height = "400px")))
dashboardBody(
  selectInput("x", "Select Filter", choices=c("month", "code"), selected="code"), 
  plotOutput("plot", width = "500px", height = "400px"))



server <- function(input, output, session) { 
 output$plot <- renderPlot({
  attjoined %>% 
  ggplot(aes_string(x = "month", y = input$y, fill=input$y)) +
  geom_col(position="dodge", alpha = 0.8, size=4)+
  theme_light(base_size = 18) + 
     labs(title= "Attendance and Enrollment by month", x="Attendance Month", y="Number of Students", fill = "Legend")+
     theme(axis.text.x = element_text(angle = 90, hjust = 1))
  })
  session$onSessionEnded(stopApp)
  }
shinyApp(ui, server)
```




